version: "3.8"

services:
  php-fpm:
    build:
      context: ./docker/config/php
      args:
        PHP_VERSION: ${DOCKER_PHP_VERSION}
        TIMEZONE: ${DOCKER_TIMEZONE}
        COMPOSER_VERSION: ${DOCKER_COMPOSER_VERSION}
    container_name: php-fpm
    restart: always
    env_file: .env
    volumes:
      - ./:/var/www/app

  nginx:
    image: nginx:${DOCKER_NGINX_VERSION}-alpine
    env_file: .env
    restart: on-failure
    container_name: nginx
    ports:
      - ${DOCKER_NGINX_EXTERNAL_PORT}:80    
    volumes:
      - ./docker/config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app

