services:
    _defaults:
        autowire: true  
        autoconfigure: true 

    App\:
        resource: '../src/*'
        exclude: '../src/{
            DependencyInjection,
            Entity,
            Exception,
            Model,
            Migrations,
            Tests,
            Kernel.php
        }'

    App\Controller\API\:
        resource: '../src/Controller/API'
        tags: ['controller.service_arguments']